### ISSUE TITLE
Import fails in PyPy

### ISSUE THREAD

**Issue by edwardreed81** [zarr-developers/numcodecs#484] opened 2023-10-20 12:09 UTC
#### Problem description

I installed numcodecs in a PyPy 3.10.12 environment using PyEnv and Poetry. Importing numcodecs fails:
```python
Python 3.10.12 (af44d0b8114cb82c40a07bb9ee9c1ca8a1b3688c, Jun 15 2023, 12:39:27)
[PyPy 7.3.12 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import numcodecs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eddie/tmp/.venv/lib/pypy3.10/site-packages/numcodecs/__init__.py", line 91, in <module>
    from numcodecs.shuffle import Shuffle
  File "/home/eddie/tmp/.venv/lib/pypy3.10/site-packages/numcodecs/shuffle.py", line 4, in <module>
    from ._shuffle import _doShuffle, _doUnshuffle
ModuleNotFoundError: No module named 'numcodecs._shuffle'
```
#### Version and installation information

* Value of ``numcodecs.__version__``
    * 0.12.1
* Version of Python interpreter
    * PyPy 3.10.12
* Operating system (Linux/Windows/Mac)
    * Linux
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda")
    * Poetry (`poetry add numcodecs`)

```
Package           Version
----------------- ------------
cffi              1.15.1
click             8.1.7
greenlet          0.4.13
hpy               0.0.4
numcodecs         0.12.1
numpy             1.26.1
packaging         23.2
pandas            2.1.1
pip               23.2.1
python-dateutil   2.8.2
pytz              2023.3.post1
readline          6.2.4.1
setuptools        68.2.0
six               1.16.0
tqdm              4.66.1
typer             0.9.0
typing_extensions 4.8.0
tzdata            2023.3
wheel             0.41.2
xarray            2023.10.0
```

**Comment by jakirkham** [comment] 2023-10-20 19:11
This is expected behavior currently. We disable compiling extensions on PyPy

https://github.com/zarr-developers/numcodecs/blob/8c4098e738e02007184a46688251718e76acc3bf/setup.py#L332-L335

Have looked before at enabling extension compilation on PyPy ( https://github.com/zarr-developers/numcodecs/pull/409 ). Though there are some issues that would need to be fixed there

If you have time, please feel free to look at the log in that PR and make suggestions

**Comment by edwardreed81** [comment] 2023-10-23 12:04
It is good to know that it is expected, but I don't have nearly the knowledge required to contribute anything useful tot that PR unfortunately.

**Comment by dstansby** [comment] 2024-10-28 22:27
Since we don't support PyPy at the moment, I'm going to close this. I think we would welcome a more general request issue for PyPy support if there is demand, especially if someone is willing to create and maintain some PyPy continuous integration.

**Closed by dstansby** 2024-10-28 22:27 UTC
